

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255),
                       cep VARCHAR(20),

                       CONSTRAINT pk_users
                           PRIMARY KEY (id),

                       CONSTRAINT uk_users_name
                           UNIQUE (name),

                       CONSTRAINT uk_users_email
                           UNIQUE (email)
);



CREATE TABLE services (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          provider VARCHAR(255),
                          title VARCHAR(255),
                          description VARCHAR(1000),
                          category VARCHAR(255),
                          price NUMERIC(10, 2),

                          CONSTRAINT pk_services
                              PRIMARY KEY (id)
);




CREATE TABLE contratations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                               contratante_id BIGINT NOT NULL,
                               service_id BIGINT NOT NULL,

                               CONSTRAINT pk_contratations
                                   PRIMARY KEY (id),

                               CONSTRAINT fk_contratations_user
                                   FOREIGN KEY (contratante_id)
                                       REFERENCES users (id),

                               CONSTRAINT fk_contratations_service
                                   FOREIGN KEY (service_id)
                                       REFERENCES services (id)
);


CREATE INDEX idx_contratations_contratante
    ON contratations (contratante_id);

CREATE INDEX idx_contratations_service
    ON contratations (service_id);