CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE contratation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contratante_id BIGINT                                  NOT NULL,
    service_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_contratation PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE service
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider    VARCHAR(255),
    title       VARCHAR(255),
    description VARCHAR(255),
    category    VARCHAR(255),
    price       DOUBLE PRECISION,
    CONSTRAINT pk_service PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255),
    cep      VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_name UNIQUE (name);

ALTER TABLE contratation
    ADD CONSTRAINT FK_CONTRATATION_ON_CONTRATANTE FOREIGN KEY (contratante_id) REFERENCES "user" (id);

ALTER TABLE contratation
    ADD CONSTRAINT FK_CONTRATATION_ON_SERVICE FOREIGN KEY (service_id) REFERENCES service (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);